[rich]
panel_style = "on #000000"
table_header_style = "bold #000000 on #c1deff"
table_title_style = "bold #ffffff"
table_border_style = "#84b0d8"
panel_border_style = "#84b0d8"
column_output = "bold #ffffff"
column_value = "#ffffff"
bright_black = "#686a66"
bright_blue = "#84b0d8"
bright_cyan = "#37e6e8"
bright_green = "#99e343"
bright_magenta = "#bc94b7"
bright_red = "#f54235"
bright_white = "#f1f1f0"
bright_yellow = "#fdeb61"
normal_black = "#000000"
normal_blue = "#427ab3"
normal_cyan = "#00a7aa"
normal_green = "#5ea702"
normal_magenta = "#89658e"
normal_red = "#d81e00"
normal_white = "#dbded8"
normal_yellow = "#cfae00"
cursor_cursor = "#ffffff"
cursor_text = "#000000"
table_show_lines = true
table_box = "HEAVY"
panel_padding = [ 1, 1,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#686a66"
blue = "#84b0d8"
cyan = "#37e6e8"
green = "#99e343"
magenta = "#bc94b7"
red = "#f54235"
white = "#f1f1f0"
yellow = "#fdeb61"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#427ab3"
cyan = "#00a7aa"
green = "#5ea702"
magenta = "#89658e"
red = "#d81e00"
white = "#dbded8"
yellow = "#cfae00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#c1deff"
text = "#000000"
